using System.Text;
using FinancialServices.Api.Connectors.Mcp;

namespace Prism.ProviderDiscovery;

/// <summary>
/// Writes the Phase-0 discovery findings note (implementationPlan/13, Round 1): the <b>real</b> tool
/// names + JSON schemas the provider's MCP server advertised, plus a <b>suggested, empty</b> field →
/// <c>ProviderRatingRecord</c> mapping template for the operator to fill. The mapping itself is Round 2;
/// this note never invents field bindings (P1 — no fabrication).
/// </summary>
public static class DiscoveryReportWriter
{
    public static async Task<string> WriteAsync(
        string outputDirectory,
        string providerLabel,
        string mcpUrl,
        IReadOnlyList<McpToolInfo> tools,
        (string Tool, McpToolCallResult Result)? sampleCall,
        CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(outputDirectory);
        var path = Path.Combine(outputDirectory, $"{providerLabel.ToLowerInvariant()}-tools.md");

        var sb = new StringBuilder();
        sb.AppendLine($"# Phase-0 discovery — {providerLabel} MCP tools");
        sb.AppendLine();
        sb.AppendLine($"**Endpoint:** `{mcpUrl}`  ");
        sb.AppendLine($"**Discovered:** {DateTimeOffset.UtcNow:u}  ");
        sb.AppendLine($"**Tool count:** {tools.Count}");
        sb.AppendLine();
        sb.AppendLine("> ⚠️ **DO NOT COMMIT.** This note can contain licensed provider data (especially any");
        sb.AppendLine("> `tools/call` sample below). It is written under the git-ignored `.prism/` directory by");
        sb.AppendLine("> default — keep it there. Redistribution of provider ratings is governed by your license.");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by `tools/ProviderDiscovery`. Tool names + schemas are the server's");
        sb.AppendLine("> real advertised contract. The field mapping below is an EMPTY template for you to");
        sb.AppendLine("> fill in Round 2 — nothing here is invented (P1).");
        sb.AppendLine();

        sb.AppendLine("## Tools (`tools/list`)");
        sb.AppendLine();
        if (tools.Count == 0)
        {
            sb.AppendLine("_No tools advertised._");
        }

        foreach (var tool in tools)
        {
            sb.AppendLine($"### `{tool.Name}`");
            if (!string.IsNullOrWhiteSpace(tool.Title))
            {
                sb.AppendLine($"**Title:** {tool.Title}  ");
            }

            if (!string.IsNullOrWhiteSpace(tool.Description))
            {
                sb.AppendLine($"**Description:** {tool.Description}");
            }

            sb.AppendLine();
            sb.AppendLine("Input JSON schema:");
            sb.AppendLine();
            sb.AppendLine("```json");
            sb.AppendLine(tool.JsonSchema);
            sb.AppendLine("```");
            sb.AppendLine();
        }

        if (sampleCall is { } call)
        {
            sb.AppendLine($"## Sample `tools/call` — `{call.Tool}`");
            sb.AppendLine();
            sb.AppendLine($"- **isError:** {call.Result.IsError}");
            sb.AppendLine();
            sb.AppendLine("Structured content:");
            sb.AppendLine();
            sb.AppendLine("```json");
            sb.AppendLine(call.Result.StructuredJson ?? "(none)");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("Text content:");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine(string.IsNullOrEmpty(call.Result.Text) ? "(none)" : call.Result.Text);
            sb.AppendLine("```");
            sb.AppendLine();
        }

        sb.AppendLine("## Suggested field → `ProviderRatingRecord` mapping (Round 2 — fill in)");
        sb.AppendLine();
        sb.AppendLine("Prism needs, per issuer, at minimum: a **letter grade**, a **rating-action date**, and a");
        sb.AppendLine("**mappable issuer id** (the STK-02 gate). Map the real schema fields above onto these:");
        sb.AppendLine();
        sb.AppendLine("| ProviderRatingRecord field | Required? | Provider tool + JSON path | Notes |");
        sb.AppendLine("|---|---|---|---|");
        sb.AppendLine("| `Letter` (string) | yes | _tool_ → `_path_` | must map onto `NotchLadder` (guarded `TryToNotch`) |");
        sb.AppendLine("| `RatingActionDate` (DateTimeOffset) | yes | _tool_ → `_path_` | missing ⇒ MISSING_COVERAGE, never `default` |");
        sb.AppendLine("| issuer id (CUSIP/ISIN/entity) | yes | _tool_ → `_path_` | unmapped ⇒ MISSING_COVERAGE, never guessed |");
        sb.AppendLine("| `Factors[]` (weight/score) | no | _tool_ → `_path_` | absent ⇒ `Array.Empty` (residual-only decomposition) |");
        sb.AppendLine("| `SourceRef` | yes | derive | provenance string, e.g. `live:" + providerLabel.ToLowerInvariant() + ":<id>` |");
        sb.AppendLine();
        sb.AppendLine("**Go/No-Go:** GO only if a tool returns a corporate-bond issuer credit rating with a letter");
        sb.AppendLine("grade + rating-action date + a mappable id. Otherwise this provider is out — say so (P1).");

        await File.WriteAllTextAsync(path, sb.ToString(), cancellationToken).ConfigureAwait(false);
        return path;
    }
}
